{
 "title": "Airflow-Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "executor_slots",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_open_slots", "legendFormat": "executor_open_slots" },
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "executor_queue_slots" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "executor_running_slots" }
   ]
  },
  {
   "title": "dag_file_processor_timeouts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_file_processor_timeouts"
    }
   ]
  },
  {
   "title": "dag_processing_processes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_processes"
    }
   ]
  },
  {
   "title": "airflow_dagbag_size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_dagbag_size" }
   ]
  },
  {
   "title": "airflow_dag_processing_import_errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors"
    }
   ]
  },
  {
   "title": "airflow_scheduler_heartbeat",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_heartbeat{type=\"counter\"}"
    }
   ]
  },
  {
   "title": "schedular_jobs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_schedulerjob_end", "legendFormat": "executor_open_slots" },
    { "expr": "airflow_schedulerjob_start", "legendFormat": "executor_queue_slots" }
   ]
  },
  {
   "title": "airflow_dag_processing_last_run_seconds_ago",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "airflow_dag_processing_last_run_seconds_ago",
     "legendFormat": "{{dag_file}}"
    }
   ]
  }
 ]
}