apiVersion: v1
kind: Pod
metadata:
  name: my-pod  #pod name
  labels:
    app: nginx #pod lables
spec:
  containers:
    - name: my-container # container's name inside pod
      image: nginx
      ports:
        - containerPort: 80
  restartPolicy: OnFailure